name: epayco_dart
description: Epayco APIfy wrapper for dart.
version: 0.0.3
repository: https://github.com/EndersonPro/epayco_dart

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  dartz: ^0.10.1
  dio: ^5.3.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
